package ru.stqa.pft.sandbox;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class FirstJavaProgram {
    public static void main(String[] args) {
        System.out.println("Hello world!");
    }
}
